-- Processed Events (for idempotency)
CREATE SEQUENCE CPS_PROC_SEQ START WITH 1 INCREMENT BY 1 CACHE 1000 NOCYCLE;

CREATE TABLE CPS_PROCESSED_EVENTS (
    EVENT_ID     VARCHAR2(100) PRIMARY KEY,
    PAYLOAD_HASH VARCHAR2(128),
    STATUS       VARCHAR2(20),
    PROCESSED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Outbox Events
CREATE SEQUENCE CPS_OUTBOX_SEQ START WITH 1 INCREMENT BY 1 CACHE 1000 NOCYCLE;

CREATE TABLE CPS_OUTBOX_EVENTS (
    EVENT_ID     NUMBER(19) PRIMARY KEY,
    EVENT_TYPE   VARCHAR2(100) NOT NULL,
    AGGREGATE_ID NUMBER(19),
    PAYLOAD      CLOB NOT NULL,
    STATUS       VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (STATUS IN ('PENDING','PUBLISHED','FAILED')),
    CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    PUBLISHED_AT TIMESTAMP
);
